#!/usr/bin/env python3
"""Cut g4.html's effects layer out into the Divi child theme.

g4.html is the source of truth for the night's animations. The Divi
edition does not want its markup or its page styling - the child theme
already has tod.css for that - only the effects, wired to the classes
Divi's layout actually emits.

Produces two generated files (do not hand-edit; edit g4.html and re-run):

    divi/child/assets/js/g4-night.js
    divi/child/assets/css/g4-night.css

What is taken, and what is left behind
--------------------------------------
JS   : the component functions, verbatim - initSplashCursor (the ported
       React Bits WebGL fluid), initNoise, initSpotlight, initMagnet,
       the two touch observers, initSectionFluid. The mount is NOT
       taken: g4 mounts against its own markup, Divi has its own, so
       this file appends a Divi mount written for Divi's DOM.
       initSpores comes along but is never called here - tod.js already
       runs it on this site, and calling it twice would draw twice.

CSS  : only the effect rules. Everything that styles the page itself
       (hero, sections, cards, type) is tod.css's job on a Divi site.

Spores and fluid are both, not either
-------------------------------------
tod.js starts spores on every device and this file leaves them alone.
They are ambient - drifting from load, asking for nothing. The fluid is
reactive: it paints where a pointer goes and, with no pointer, paints
nothing. Neither substitutes for the other, so a cursor device gets
spores in the header AND the fluid across the page. (An earlier version
deleted the .tod-atmo host when a cursor was present; that was an
aesthetic call, not a technical one, and it was wrong.)

Usage: python3 scripts/build-g4-divi.py
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "g4.html")
JS_OUT = os.path.join(ROOT, "divi", "child", "assets", "js", "g4-night.js")
CSS_OUT = os.path.join(ROOT, "divi", "child", "assets", "css", "g4-night.css")

BANNER = ("/* GENERATED by scripts/build-g4-divi.py from g4.html - do not edit.\n"
          "   Edit g4.html and re-run the script. */\n\n")


class Fail(Exception):
    pass


def slice_between(text, start_marker, end_marker, what):
    """Take the text between two markers, refusing to guess if either moved."""
    i = text.find(start_marker)
    if i < 0:
        raise Fail(f"start marker for {what} not found: {start_marker!r}")
    j = text.find(end_marker, i)
    if j < 0:
        raise Fail(f"end marker for {what} not found: {end_marker!r}")
    return text[i:j]


def read_source():
    with open(SRC, encoding="utf-8") as fh:
        return fh.read()


def extract_style(html):
    m = re.search(r"(?s)<style>(.*?)</style>", html)
    if not m:
        raise Fail("no <style> block in g4.html")
    return m.group(1)


def extract_script(html):
    lines = html.split("\n")
    try:
        i = next(n for n, l in enumerate(lines) if l.strip() == "<script>")
        j = next(n for n, l in enumerate(lines) if l.strip() == "</script>")
    except StopIteration:
        raise Fail("no <script> block in g4.html")
    return "\n".join(lines[i + 1:j])


# ---------------------------------------------------------------- CSS

# Each entry is (start marker, end marker). The end marker is the first
# line of whatever comes next, so a reordered stylesheet fails loudly
# instead of silently taking the wrong rules.
CSS_BLOCKS = [
    ("/* --- SplashCursor: the fluid, fixed over the whole page --------",
     "/* --- Noise: the library's grain canvas"),
    ("/* --- Noise: the library's grain canvas",
     "/* --- StarBorder: two radial gradients travelling the long way"),
    ("/* --- StarBorder: two radial gradients travelling the long way",
     "/* --- SpotlightCard: radial glow tracking the pointer -----------"),
    ("/* --- SpotlightCard: radial glow tracking the pointer -----------",
     "/* --- GlareHover: a sheen sweeping across on hover --------------"),
    ("/* --- GlareHover: a sheen sweeping across on hover --------------",
     "/* --- Magnet: wrapper is static, inner one gets the translate ---"),
    ("/* --- Magnet: wrapper is static, inner one gets the translate ---",
     "/* ============================================================\n   14"),
    ("/* A SplashCursor bed scoped to one section",
     "/* spores drift up in here on touch devices"),
    ("/* --- touch: the two hover-driven bits, driven by the viewport ---",
     "/* --- no cursor, no cursor effects ------------------------------"),
    ("/* --- no cursor, no cursor effects ------------------------------",
     "/* ============================================================\n   15"),
]

CSS_TAIL = """
/* ------------------------------------------------------------------
   Divi wiring. The classes above are g4's; these are the ones Divi's
   layout emits. The JS adds g4's class to each, so every rule above
   applies unchanged rather than being duplicated for Divi's markup.
   Listed here only for the two that need a size or a stacking context.
   ------------------------------------------------------------------ */

/* Selectors here are deliberately OURS, not Divi's. Divi 5.11 still
   emits et_pb_* on the front end (it renders the D4 layouts through its
   legacy framework), but a page re-saved in the D5 Visual Builder
   converts to the block format, and nothing promises those generated
   class names survive it. module_id and module_class do survive - Divi
   carries them through either format - so everything below hangs off
   the ids and classes divi/layouts/ sets itself. */

/* a section holding a fluid bed must be a positioning context, and its
   own content has to sit above the canvas */
.g4-has-bed{ position:relative; }
.g4-has-bed > *:not(.fluid-bed){ position:relative; z-index:1; }

/* gallery tiles become GlareHover tiles */
.h-gallery-divi .g4-tile{ position:relative; overflow:hidden; }

/* .spotlight brings a card's padding with it; tod.css already gave the
   date row its own, so hand it back. .spotlight-row covers the rest
   (background, border, radius). */
.tod-date.spotlight{ padding:1rem .2rem; }
"""


def build_css(style):
    out = [BANNER.replace("/*", "/*", 1)]
    for start, end in CSS_BLOCKS:
        out.append(slice_between(style, start, end, start[:48]).rstrip() + "\n\n")
    out.append(CSS_TAIL)
    return "".join(out)


# ---------------------------------------------------------------- JS

JS_START = "function initSplashCursor(canvas, options) {"
JS_END = "  /* the logo's equalizer, alive */"

JS_MOUNT = r"""
  /* ==================================================================
     The Divi mount. g4 mounts against its own markup; this mounts
     against the classes divi/layouts/ actually emits:

       module_id   top  story  sets  dates  photos  contact
       classes     tod-artist  h-set  h-gallery-divi  tod-reveal

     Everything tod.js already does on this site - spores, flicker-on
     titles, reveals, tilt, the equalizer - is left to tod.js.
     ================================================================== */

  const BED_SECTIONS = ['story', 'sets', 'dates', 'contact'];

  const el = (tag, id, cls) => {
    const n = document.createElement(tag);
    if (id) n.id = id;
    if (cls) n.className = cls;
    n.setAttribute('aria-hidden', 'true');
    return n;
  };

  ready(function () {
    if (REDUCED) return;

    /* the hover-driven pieces, on the modules Divi gives them to */
    for (const n of document.querySelectorAll('.h-set')) {
      n.classList.add('spotlight');
      n.setAttribute('data-spotlight', '');
    }

    /* Date rows get the flat variant: same pointer glow, but no card
       background, border or radius - .tod-date already has its own. */
    for (const n of document.querySelectorAll('.tod-date')) {
      n.classList.add('spotlight', 'spotlight-row');
      n.setAttribute('data-spotlight', '');
    }
    /* Divi names gallery items itself and the name is version-shaped,
       so match loosely and fall back to whatever wraps the images. */
    const gal = document.querySelector('.h-gallery-divi');
    if (gal) {
      const tiles = gal.querySelectorAll('[class*="gallery_item"], [class*="gallery-item"]');
      for (const n of (tiles.length ? tiles : gal.querySelectorAll('img'))) {
        n.classList.add('glare', 'g4-tile');
      }
    }

    for (const n of document.querySelectorAll('[data-spotlight]')) initSpotlight(n);

    if (!HAS_CURSOR) {
      /* touch: no fluid overlay, no grain, no magnet. A bed per named
         section instead, and the two hover effects driven by the
         viewport. Spores stay with tod.js, in the hero, where they are. */
      for (const id of BED_SECTIONS) {
        const section = document.getElementById(id);
        if (!section || section.querySelector('.fluid-bed')) continue;
        section.classList.add('g4-has-bed');
        section.prepend(el('div', null, 'fluid-bed'));
      }
      initSectionFluid();
      initTouchGlare();
      initTouchSpotlight();
      return;
    }

    /* cursor: the night's full atmosphere over the whole document */
    document.body.append(el('canvas', 'grain'), el('canvas', 'fluid'));

    initNoise(document.getElementById('grain'), { patternAlpha: 12 });

    /* the parameters from the Background Studio, as given */
    initSplashCursor(document.getElementById('fluid'), {
      SIM_RESOLUTION: 128,
      DYE_RESOLUTION: 1440,
      DENSITY_DISSIPATION: 3.5,
      VELOCITY_DISSIPATION: 2,
      PRESSURE: 0.1,
      CURL: 3,
      SPLAT_RADIUS: 0.2,
      SPLAT_FORCE: 6000,
      COLOR_UPDATE_SPEED: 14
    });
  });
})();
"""

JS_HEAD = r"""(function () {
  'use strict';

  const REDUCED = matchMedia('(prefers-reduced-motion: reduce)').matches;
  const HAS_CURSOR = matchMedia('(hover: hover) and (pointer: fine)').matches;

  const ready = fn => {
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', fn);
    else fn();
  };

"""


def build_js(script):
    body = slice_between(script, JS_START, JS_END, "component functions")
    if "initSplashCursor" not in body or "initTouchSpotlight" not in body:
        raise Fail("component slice is missing expected functions")
    return BANNER + JS_HEAD + body.rstrip() + "\n" + JS_MOUNT


def verify(js, css):
    checks = [
        ("fluid sim present", "gl.createProgram" in js or "createShader" in js),
        ("auto-splat option", "AUTO_SPLAT_MS" in js),
        ("pause/resume", "resume:" in js and "pause:" in js),
        ("no g4 mount leaked", "initWave" not in js),
        ("no var", not re.search(r"\\bvar\\s+\\w", js)),
        ("spores present but never called",
         "initSpores" in js
         and not re.search(r"^\\s*initSpores\\(\\);", js, re.M)),
        ("divi mount present", "BED_SECTIONS" in js),
        ("fluid css", "#fluid{" in css),
        ("bed css", ".fluid-bed{" in css),
        ("touch block", "(hover:none)" in css),
        ("no page layout css", ".hero-title" not in css and ".h2{" not in css),
    ]
    bad = [name for name, ok in checks if not ok]
    if bad:
        raise Fail("verification failed: " + ", ".join(bad))
    return checks


def main():
    html = read_source()
    css = build_css(extract_style(html))
    js = build_js(extract_script(html))
    checks = verify(js, css)

    for path, text in ((JS_OUT, js), (CSS_OUT, css)):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"  wrote {os.path.relpath(path, ROOT):44s} {len(text):6d} bytes")
    for name, _ in checks:
        print(f"    ok  {name}")


if __name__ == "__main__":
    try:
        main()
    except Fail as exc:
        print(f"build-g4-divi: {exc}", file=sys.stderr)
        sys.exit(1)
